/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ChunksRouteImport } from './routes/chunks'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ListenIdRouteImport } from './routes/listen.$id'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ChunksRoute = ChunksRouteImport.update({
  id: '/chunks',
  path: '/chunks',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListenIdRoute = ListenIdRouteImport.update({
  id: '/listen/$id',
  path: '/listen/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chunks': typeof ChunksRoute
  '/search': typeof SearchRoute
  '/listen/$id': typeof ListenIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chunks': typeof ChunksRoute
  '/search': typeof SearchRoute
  '/listen/$id': typeof ListenIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chunks': typeof ChunksRoute
  '/search': typeof SearchRoute
  '/listen/$id': typeof ListenIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/chunks' | '/search' | '/listen/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/chunks' | '/search' | '/listen/$id'
  id: '__root__' | '/' | '/chunks' | '/search' | '/listen/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChunksRoute: typeof ChunksRoute
  SearchRoute: typeof SearchRoute
  ListenIdRoute: typeof ListenIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chunks': {
      id: '/chunks'
      path: '/chunks'
      fullPath: '/chunks'
      preLoaderRoute: typeof ChunksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listen/$id': {
      id: '/listen/$id'
      path: '/listen/$id'
      fullPath: '/listen/$id'
      preLoaderRoute: typeof ListenIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChunksRoute: ChunksRoute,
  SearchRoute: SearchRoute,
  ListenIdRoute: ListenIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
