"""baseline schema

Revision ID: 1b329637734b
Revises:
Create Date: 2026-06-28 02:15:55.860310

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1b329637734b"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "videos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("youtube_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("youtube_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("duration", sa.Integer(), nullable=False),
        sa.Column("transcript", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("full_transcript_data", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_videos_youtube_id"), "videos", ["youtube_id"], unique=True)
    op.create_table(
        "chunks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("video_id", sa.Integer(), nullable=False),
        sa.Column("phrase", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("phrase_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("start_time", sa.Float(), nullable=False),
        sa.Column("prompts", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["video_id"],
            ["videos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("video_id", "phrase_key", name="uq_chunks_video_phrase"),
    )
    op.create_index(op.f("ix_chunks_phrase_key"), "chunks", ["phrase_key"], unique=False)
    op.create_index(op.f("ix_chunks_video_id"), "chunks", ["video_id"], unique=False)
    op.create_table(
        "frase_exercise",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("video_id", sa.Integer(), nullable=False),
        sa.Column("start_time", sa.Float(), nullable=False),
        sa.Column("end_time", sa.Float(), nullable=False),
        sa.Column("original_transcript_text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("exercise_text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("answers", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("hints", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("difficulty", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["video_id"], ["videos.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_frase_exercise_video_id"), "frase_exercise", ["video_id"], unique=False
    )
    op.create_table(
        "phrase_autopsy",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("video_id", sa.Integer(), nullable=False),
        sa.Column("phrase", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("phrase_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("start_time", sa.Float(), nullable=False),
        sa.Column("register", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("grammar", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("natural_notes", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["video_id"],
            ["videos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("video_id", "phrase_key", name="uq_phrase_autopsy_video_key"),
    )
    op.create_index(
        op.f("ix_phrase_autopsy_phrase_key"), "phrase_autopsy", ["phrase_key"], unique=False
    )
    op.create_index(
        op.f("ix_phrase_autopsy_video_id"), "phrase_autopsy", ["video_id"], unique=False
    )
    op.create_table(
        "processing_jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("flow_run_id", sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
        sa.Column("youtube_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("youtube_video_id", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("video_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "status IN ('PENDING','RUNNING','COMPLETED','FAILED')", name="ck_processing_jobs_status"
        ),
        sa.ForeignKeyConstraint(["video_id"], ["videos.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_processing_jobs_created_at"), "processing_jobs", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_processing_jobs_flow_run_id"), "processing_jobs", ["flow_run_id"], unique=True
    )
    op.create_index(op.f("ix_processing_jobs_status"), "processing_jobs", ["status"], unique=False)
    op.create_index(
        op.f("ix_processing_jobs_video_id"), "processing_jobs", ["video_id"], unique=False
    )
    op.create_index(
        op.f("ix_processing_jobs_youtube_video_id"),
        "processing_jobs",
        ["youtube_video_id"],
        unique=False,
    )
    op.create_table(
        "questions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("video_id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.Float(), nullable=False),
        sa.Column("question", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("answers", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("correct_answer", sa.Integer(), nullable=False),
        sa.Column("explanation", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["video_id"],
            ["videos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_questions_video_id"), "questions", ["video_id"], unique=False)
    op.create_table(
        "video_segments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("video_id", sa.Integer(), nullable=False),
        sa.Column("segment_number", sa.Integer(), nullable=False),
        sa.Column("transcript_text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("start_time", sa.Float(), nullable=False),
        sa.Column("end_time", sa.Float(), nullable=False),
        sa.Column("tokens", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["video_id"],
            ["videos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_video_segments_video_id"), "video_segments", ["video_id"], unique=False
    )
    op.create_table(
        "answer_progress",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("video_id", sa.Integer(), nullable=False),
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("user_answer", sa.Integer(), nullable=False),
        sa.Column("is_correct", sa.Boolean(), nullable=False),
        sa.Column("answered_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["question_id"], ["questions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["video_id"], ["videos.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("video_id", "question_id", name="unique_video_question_progress"),
    )
    op.create_index(
        op.f("ix_answer_progress_question_id"), "answer_progress", ["question_id"], unique=False
    )
    op.create_index(
        op.f("ix_answer_progress_video_id"), "answer_progress", ["video_id"], unique=False
    )
    op.create_table(
        "recordings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("chunk_id", sa.Integer(), nullable=False),
        sa.Column("file_path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("content_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["chunk_id"], ["chunks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_recordings_chunk_id"), "recordings", ["chunk_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_recordings_chunk_id"), table_name="recordings")
    op.drop_table("recordings")
    op.drop_index(op.f("ix_answer_progress_video_id"), table_name="answer_progress")
    op.drop_index(op.f("ix_answer_progress_question_id"), table_name="answer_progress")
    op.drop_table("answer_progress")
    op.drop_index(op.f("ix_video_segments_video_id"), table_name="video_segments")
    op.drop_table("video_segments")
    op.drop_index(op.f("ix_questions_video_id"), table_name="questions")
    op.drop_table("questions")
    op.drop_index(op.f("ix_processing_jobs_youtube_video_id"), table_name="processing_jobs")
    op.drop_index(op.f("ix_processing_jobs_video_id"), table_name="processing_jobs")
    op.drop_index(op.f("ix_processing_jobs_status"), table_name="processing_jobs")
    op.drop_index(op.f("ix_processing_jobs_flow_run_id"), table_name="processing_jobs")
    op.drop_index(op.f("ix_processing_jobs_created_at"), table_name="processing_jobs")
    op.drop_table("processing_jobs")
    op.drop_index(op.f("ix_phrase_autopsy_video_id"), table_name="phrase_autopsy")
    op.drop_index(op.f("ix_phrase_autopsy_phrase_key"), table_name="phrase_autopsy")
    op.drop_table("phrase_autopsy")
    op.drop_index(op.f("ix_frase_exercise_video_id"), table_name="frase_exercise")
    op.drop_table("frase_exercise")
    op.drop_index(op.f("ix_chunks_video_id"), table_name="chunks")
    op.drop_index(op.f("ix_chunks_phrase_key"), table_name="chunks")
    op.drop_table("chunks")
    op.drop_index(op.f("ix_videos_youtube_id"), table_name="videos")
    op.drop_table("videos")
    # ### end Alembic commands ###
